### ISSUE TITLE
media:type and media:end

### ISSUE THREAD

**Issue by pw374** [ocaml/omd#106]
**_edit: `media:end` is no longer supported as the problem it addressed was solved else way.**_

`media:type="text/omd"` introduced a hard problem: it can become impossible to really know where an HTML block ends. For instance, see this:

```
<div media:type="text/omd">
    </div> (4 spaces so is it code or the end of the div?)
</div>
```

or even this:

```
<div media:type="text/omd">
</div> (no 4 spaces, so it's not code, but it'd be valid Markdown since non-valid HTML in markdown is just not HTML)
</div>
```

So, I've introduced (in 5100c95e41926d5775d7d6311a7b9e3de847edda and 42dabc469418a3c13b532421433ac41c76c51637) `media:end` to give a string that will give a hint on where to stop.

Here's an example:

```
$ ./omd <<< '<div media:type="text/omd" media:end="!stop" >food</div>!stop</div> plop'
<div><p>food&lt;/div&gt;</p>
</div>
<p> plop</p>
```

However, at least for now, it will only work if the value of `media:end` is a string that is **easy enough** to find! Due to the token representation in OMD, it's somewhat difficult to find something like `!foo` in `!!!foobar` because the representation for the former 
 is `[Exclamation;Word "foo"]` while for the latter it's `[Exclamations 1;Word "foobar"]`. 
So it will not work (at least at the time I'm writing these words) with say `<div media:type="text/omd" media:end="stop" >busstop</div>` but it will with `<div media:type="text/omd" media:end="stop" >bus stop</div>` or with `<div media:type="text/omd" media:end="!stop" >bus!stop</div>`.

If the value of `media:end` is not found, the default algorithm (to search the end of the HTML block) is used, it will not fail. Just as `media:type="text/omd"`, if it is seen, it is removed. (Since there's only partial nesting handling, it's very possible that a `media:end` is never seen as an HTML tag, and in such case they're not removed nor do they have any specific semantics).

_Please feel free to comment if you have any thoughts about that._

**Comment by nojb** [comment]
This `media` stuff is no longer supported in `master` as it is not standard markdown. We will be looking at how to support extensions after we get 2.0 out the door.
