### ISSUE TITLE
Don't handle escaping double backslash (\\\\)

### ISSUE THREAD

**Issue by tinara** [ocaml/omd#114]
OMD doesn't parse right double backslash escaping. For example, `\\\\` ouputs nothing (in fact, it ouputs an end-of-line `\n`) instead of `\\`.

**Comment by TheoWinterhalter** [comment]
Hi, I have a similar issue, I want to use MathJax/KaTeX with omd, but `\(` is output as `(` so I have to use `\\(` in the code. It doesn't work with `\\]` which outputs `\\]`, while `\]` outputs `]`.

**Comment by pw374** [comment]
@TheoWinterhalter can you try using? It might solve your issue (I'm pretty sure it will solve the backslashing thing, but I'm not sure it won't create other issues because that's a version that wasn't released).
```
opam pin add omd  https://github.com/ocaml/omd.git#fd7fa4e129ce594a62f34b2f3ad97ce7329e3e69
```

Also, commenting a closed issue is not really a good thing to do: you should've opened a new issue and reference this one! ;)

**Comment by TheoWinterhalter** [comment]
@pw374 Thank you, and sorry for not opening a new issue, should I still do it?
The whole interface changes with 2.0.0 (and there is no documentation that I can see), I'm not using the binary, but the library so it's a bit painful.

**Comment by nojb** [comment]
> The whole interface changes with 2.0.0 (and there is no documentation that I can see), I'm not using the binary, but the library so it's a bit painful.

Yes, apologies for that. 2.0 has a different (simpler, I think) API. Some aspects of it are still changing which is why there hasn't been a release yet. There will be documentation at the time of release.

**Comment by TheoWinterhalter** [comment]
I see, in that case, I'd rather wait for a release. My project is to built by different people so it'd be easier with a release.
