### ISSUE TITLE
support wiki style links

### ISSUE THREAD

**Issue by agarwal** [ocaml/omd#117]
If you use GitHub's wiki feature, then you have to write links to other wiki pages with double brackets, e.g. `[[Another Page]]`. Thus, it would be nice if such links are recognized by OMD. The desired behavior would be:

```
$ echo "[[Another Page]]" | omd
<a href="Another-Page.html">Another Page</a>
```

The link text automatically implies a file name, where spaces are replaced with dashes. It is also allowed to specify a file name explicitly. We would want:

```
$ echo "[[Another Page|another_page]]" | omd
<a href="another_page.html">Another Page</a>
```

This would allow importing GitHub wikis into ocaml.org, which was suggested by @avsm in [this thread](http://lists.ocaml.org/pipermail/platform/2014-April/000485.html).

**Comment by nojb** [comment]
This is not standard markdown and feels like it would be a bit of a stretch to support in the library. But if there is a specification for the extension maybe it can be added to #205
