### ISSUE TITLE
Follow the POSIX guidelines for the command-line options

### ISSUE THREAD

**Issue by Chris00** [ocaml/omd#124]
Options using more than 1 char should be preceded by 2 dashes.  E.g. `--version` and _not_ `-version`.  (Also the comment for `--version` should be aligned with the other ones — a space is missing.)

**Comment by nojb** [comment]
For now, `omd` does not have *any* dependencies. If we decide to allow dependencies, we will switch to `cmdliner` which offers all these kinds of goodies.
