### ISSUE TITLE
Verify new list of accepted HTML tags

### ISSUE THREAD

**Issue by pw374** [ocaml/omd#127]
`html`, `head`, `body`, `title`, `style`, `link` and `meta` have been accepted since https://github.com/ocaml/omd/commit/78e4708b9f1553dbeca50ece12516ed6c007bf2e.

That makes sense thanks to `media:type="text/omd"` and because the HTML parser was rewritten to be a lot more powerful than the one used when that feature was introduced.

Now someone (perhaps me, but not right now) should check that the few lists of HTML tags are what they should be.

**Comment by irskep** [comment]
I know this is a super old issue, and this project may not be maintained anymore, but I have a bit of a strange perspective on this that I'd like to share.

Allowing arbitrary HTML tags makes it possible for others to use the parser to add basic extensions using HTML tag syntax. In the same vein, allowing semicolons makes those extensions namespaceable.

As the author of a [documentation tool that does this kind of thing (but in Python)](http://steveasleep.com/computerwords/), I'd love to be able to try something similar in OCaml.
