### ISSUE TITLE
support for more pandoc extensions

### ISSUE THREAD

**Issue by edwintorok** [ocaml/omd#131]
Going through some markdown files I wrote here are some extensions that are not supported by omd:
[Title block](http://johnmacfarlane.net/pandoc/README.html#extension-pandoc_title_block)
[Superscript,subscript](http://johnmacfarlane.net/pandoc/README.html#superscripts-and-subscripts)
[Raw html](http://johnmacfarlane.net/pandoc/README.html#extension-raw_html) for `<img>` tags.
[TeX math dollars](http://johnmacfarlane.net/pandoc/README.html#extension-tex_math_dollars)

**Comment by nojb** [comment]
Moved this one to #205
