### ISSUE TITLE
Inline HTML Vs empty lines Vs Markdown between HTML tags

### ISSUE THREAD

**Issue by smondet** [ocaml/omd#160]
My understanding is that the empty line after `<summary>` should make the parser
go back to transforming markdown (`pandoc` & `github` seem to agree on the behavior), but I'm not sure.

```
 $ printf "Hello\n\n<details>\n\n**Some details**\n\n</details>\n\n"
Hello

<details>

**Some details**

</details>

 $ printf "Hello\n\n<details>\n\n**Some details**\n\n</details>\n\n" | pandoc
<p>Hello</p>
<p><details></p>
<p><strong>Some details</strong></p>
<p></details></p>

 $ printf "Hello\n\n<details>\n\n**Some details**\n\n</details>\n\n" | omd
<p>Hello</p>
<details>

**Some details**

</details>
```

And Github:

--------------------------------------------------------------------------------

Hello

<details>

**Some details**

</details>

--------------------------------------------------------------------------------

**Comment by pw374** [comment]
I'm pretty sure it was implemented like that on purpose. But maybe it was the wrong choice...

OK, I found what happened back then: #96 
In short:
```
$ printf "Hello\n\n<details media:type='text/omd'>\n\n**Some details**\n\n</details>\n\n" |omd 
<p>Hello</p>
<details>

<p><strong>Some details</strong></p>
</details>
```


P.S. Sorry I haven't seen your message earlier.

**Comment by pw374** [comment]
Since 2013, some important changes have happened in HTML and CSS.
Maybe it doesn't make sense anymore that we have both HTML inline and HTML block elements.
I've been thinking about implementing OMD**2**, a much simplified and even faster implementation of OMD. Not sure I'll ever have the time though.
