### ISSUE TITLE
Omd_lexer.destring_of_tokens represents one backslash as two backslashes

### ISSUE THREAD

**Issue by d4h0** [ocaml/omd#168]
Hi,

As the title says, Omd_lexer.destring_of_tokens represents one backslash as two backslashes:

```
utop # print_endline (Omd_lexer.destring_of_tokens (Omd_lexer.lex {|\|}));;
\\::[]
- : unit = ()
```

Is that the intended behaviour?

I was expecting it would be represented as one backslash.

Best regards,
Daniel

**Comment by pw374** [comment]
Yes it's intended. It's a function that's used for debugging and the output will be OCaml-style escaped strings. So, `\` becomes `\\`, just like `"` becomes `\"`.

More precisely, I'll just copy-paste OCaml's documentation:
> All characters outside the ASCII printable range (32..126) are escaped, as well as backslash and double-quote.
