### ISSUE TITLE
complete the Text and Markdown output targets

### ISSUE THREAD

**Issue by avsm** [ocaml/omd#181]
@nojb wrote:
> The Markdown->{Text,Markdown,HTML,...} converters need some more work. Only the HTML one is complete as far as I know (it is needed for the tests).

*(this is tracking blockers to a new omd release from #174)*

**Comment by nojb** [comment]
This has been reworked in `master` in a different way (I introduced an intermediate language for HTML, the text backend is based off that, and removed the markdown "backend" which was not used and was incomplete).
