### ISSUE TITLE
reimplement the CLI driver using new interfaces

### ISSUE THREAD

**Issue by avsm** [ocaml/omd#183]
From @nojb:
> The driver program has been stripped of almost all its options and needs to be rebuilt using the new Markdown representation. It should be easy.

*(this is tracking blockers to a new omd release from #174)*

**Comment by nojb** [comment]
For now, we are going to stay minimalistic, and try to get a 2.0 alpha out the door. We will then gauge which options are necessary and re-implement them as needed.
