### ISSUE TITLE
improve some tricky parsing corner cases and tests

### ISSUE THREAD

**Issue by avsm** [ocaml/omd#184]
from @nojb:
> Parsing: the parsing of Markdown is two-stage: first one decodes the block structure (paragraphs, lists, list items, quotes, etc.) and then one has to parse the inline structure inside each block (emphasis and links).
> The first part of the parsing can process the content line-by-line and is fairly simple. The inline part is rather tricky. Both parts are now using some variation of combinator parsing that get the job done, but am not very happy with.
> Maybe a combination of regular expressions and code could work better. Definitely something that needs looking at. More importantly the logic that parses the inline structure is way too complicated and needs to be simplified.
> A couple of tests (with tricky inline structure) fail.

*(this is tracking blockers to a new omd release from #174)*

**Comment by nojb** [comment]
Strictly speaking, not a blocker, since the current parser (if not pretty) does pretty well (it only fails about a dozen tests out of the ~650 of the testsuite).
