### ISSUE TITLE
Feature request: handle extended markdown

### ISSUE THREAD

**Issue by rjbou** [ocaml/omd#188]
`omd` is used by opam2web, to generate opam.ocaml.org pages. Table rendering is now handled by omd as a plain text. It is one of the feature of the [extended syntax](https://www.markdownguide.org/extended-syntax).

I can share an image example if needed.

**Comment by nojb** [comment]
I agree that tables are useful to have. GFM-style tables are a suitably design, I think. Now all we need is an implementation.

**Comment by avsm** [comment]
This would be useful for RWO as well; we could do this as part of that effort once the RWO build migrates to omd master (cc @clecat )

**Comment by clecat** [comment]
It seems nice to do, I will see if I can do that as a secondary effect of my work on the migration

**Comment by XVilka** [comment]
To date, most of the Markdown parsers and producers support at least some of the extensions, so having them indeed is very useful.

**Comment by nojb** [comment]
We are planning to have them. But for the initial release of version 2 (which we are working to have out the door as soon as possible), we are going to focus on having strict commonmark compatibility. Extensions will come after that. Thanks!

**Comment by nojb** [comment]
Moved this one to #205
