### ISSUE TITLE
Remove newline in raw text

### ISSUE THREAD

**Issue by clecat** [ocaml/omd#189]
Omd actually keeps newline from markdown files when dumping to html:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper sit amet
ligula sed semper. Maecenas euismod nisi sed est aliquam dignissim eu sed
lacus.
```
The previous md file would give:
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper sit amet
ligula sed semper. Maecenas euismod nisi sed est aliquam dignissim eu sed
lacus.</p>
```
Maybe we should remove the newlines and generate this instead ?
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper sit amet ligula sed semper. Maecenas euismod nisi sed est aliquam dignissim eu sed lacus.</p>
```

**Comment by nojb** [comment]
There is no difference in the rendered HTML, right? What is the rationale for changing it?

**Comment by clecat** [comment]
Indeed it has no difference, it was just for more clarity (having the paragraphs holding in a single line, it is not really important however, as not many people reads html files)

**Comment by nojb** [comment]
Yes, and also this can result in overly long lines which are difficult to read :)
