### ISSUE TITLE
Allowing support for Divs and Spans

### ISSUE THREAD

**Issue by clecat** [ocaml/omd#190]
I'm currently working on replacing pandoc for omd in mdx.
But RWO which uses mdx, is currently making use of an extension of pandoc allowing to generate [divs and spans](https://pandoc.org/MANUAL.html#divs-and-spans) in the html.

Fenced divs can be defined by using a succession of at least 3 semi-columns:
```
::::: {#fenced-div}
Foo
:::::
```
Which would give
```
<div id="fenced-div">
<p>Foo</p>
</div>
```

Spans syntax is close to the syntax of links:
```
[Span]{.class}
```
Which would give
```
<p><span class="class">Span</span></p>
```

Could it be possible to add it's support in omd ?
I would be glad to do it if you agreed with the idea.

**Comment by clecat** [comment]
Also, I would had the support for the fenced divs attributes which I dropped in [this pull request](https://github.com/ocaml/omd/pull/187) as we did not support them for now

**Comment by nojb** [comment]
Sorry, I am not familiar with this functionality. Do I understand correctly that the intention is to make `div`s with markdown block content and similarly `span`s with markdown inline content inside?

**Comment by clecat** [comment]
Yes my bad, I was not really clear, that's exactly the idea

**Comment by nojb** [comment]
It seems to me that the best would be to allow these two kinds of extensions (one for block content and one for inline content) in a generic way and allow the clients of the library to interpret the extensions as they want.

For example we could have `{!foo: <inline>}` and
```
<!foo>
<block content>
</!foo>
```

These would be represented by special nodes in the AST with the tag ("foo") and the content. These nodes would be rejected by the AST printers. It would be the responsibility of the library user to, either 1) rewrite the AST replacing these nodes by non-extension ones, or 2) extend the printers to handle the extension nodes.

The syntax above is just a placeholder, and it needs to have a low likelyhood of being confused with usual markdown (and be easy to parse).

What do you think?

A possible approach would be:
1) add the new extension nodes to the AST, rejecting them if they reach the printers
2) define a generic interface to the printers that allows overloading the treatment of extension nodes (an easy way is to use a record in "open recursion" style)
3) decide a syntax and implement a parser for it

**Comment by clecat** [comment]
I'm okay with that, I was going to ask you for a way to have extensions.
I'm just not sure about what you mean with "decide a syntax and implement a parser".
Do you mean that:
- a user needs a parser and a printer for his extension
- or he needs only the printer, and the extensions follows a common syntax

I personally prefer the first choice, but I'm not sure it's the one you want:
It could be nice to have a way to had specific parsers for inline content and blocks so people who already have existing markdown files doesnt need to change them in order to use omd instead of other tools.

**Comment by nojb** [comment]
> or he needs only the printer, and the extensions follows a common syntax

Definitely the second one. Having user-defined syntaxes is a recipe for disaster and almost impossible to make it work (see camlp4).

**Comment by nojb** [comment]
> decide a syntax and implement a parser for it

By this I mean simply that we should decide on a common syntax for extensions and implement a parser for it :)

**Comment by clecat** [comment]
I see what you mean.
But could have "2" systems of extensions then ?
- The first one would allow a user to use pre-defined extensions. Those extensions would have a pre-defined syntax (like the `:::` for divs) but they would only be defined by the library, and therefore be safer (the user will never be allowed to create his own parser for that)
- And the second one, (which could be an extension from the system above) would allow a user to create special block using a syntax we defined and add a printer for them. (the one you mentionned earlier).

This way, people wanting to do new things could do them with the extension allowing to add their own printers.
And on the other way, common extensions which uses a well-defined syntax could still be implemented by us (eg. attributes, divs, tables etc) so the user does not have to change his markdown files when moving to omd

**Comment by nojb** [comment]
> * The first one would allow a user to use pre-defined extensions. Those extensions would have a pre-defined syntax (like the `:::` for divs) but they would only be defined by the library, and therefore be safer (the user will never be allowed to create his own parser for that)
> * And the second one, (which could be an extension from the system above) would allow a user to create special block using a syntax we defined and add a printer for them. (the one you mentionned earlier).

Sorry I don't understand the difference; who is "we" here, the user of the library or us, the developers of the library?

> This way, people wanting to do new things could do them with the extension allowing to add their own printers.
> And on the other way, common extensions which uses a well-defined syntax could still be implemented by us (eg. attributes, divs, tables etc) so the user does not have to change his markdown files when moving to omd

Given that there is no standard spec for these extensions, it is not realistic to expect to keep unmodified markdown when porting from a different dialect of markdown, so I don't think this should be a goal for the design of this feature.

To be clear, I think the user of the library should **not** be allowed to extend the parser, under any circumstances. Rather (and this is my previous proposal) we should allow to "tag" markdown content (both in block and inline position) and to extend the printer to interpret the tag any way they see fit.

**Comment by clecat** [comment]
> Sorry I don't understand the difference; who is "we" here, the user of the library or us, the developers of the library?

I meant the developers by we, sorry

> Given that there is no standard spec for these extensions, it is not realistic to expect to keep unmodified markdown when porting from a different dialect of markdown, so I don't think this should be a goal for the design of this feature.
To be clear, I think the user of the library should not be allowed to extend the parser, under any circumstances. Rather (and this is my previous proposal) we should allow to "tag" markdown content (both in block and inline position) and to extend the printer to interpret the tag any way they see fit.

I'm totally okay with that, but what would we do for the extensions which are still pretty common (like extended markdown which was mentioned in this [issue](https://github.com/ocaml/omd/issues/188)) ?

**Comment by nojb** [comment]
I think we need to consider extensions on a case-by-case basis. For the case of tables I think we should add support for them, probably following Github Markdown for the design.

**Comment by clecat** [comment]
Okay, I will give a go to that "tagging" extension, and proposed predefined printers for Divs and Spans, I'll go for the extended markdown later

**Comment by nojb** [comment]
> Okay, I will give a go to that "tagging" extension, and propose predefined printers for Divs and Spans

I don't think we should propose any predefined printers for divs and spans; rather we should provide the ability to extend the printer to handle these extension nodes; the user of the library can then make use of this to implement "divs and spans" in their own code.

**Comment by nojb** [comment]
I think this was implemented by @clecat. We are discussing whether this will go into 2.0 or not (since we don't have a proper extension API yet and we are aiming for strict commonmark compatibility for the first release), but in any case I think the issue can be closed.
