### ISSUE TITLE
colon after closing square bracket

### ISSUE THREAD

**Issue by zapashcanon** [ocaml/omd#193]
Hi,

I'm using [stone] which produces HTML from md files and I think the following issue is from omd.

When you write:

```md
* [github]: the github website

[github]: https://github.com/
```

The first `[github]:` isn't displayed, it gives:

* the github website

When it should produce:

* [github]: the github website

If I put a space between the colon and the closing square bracket like this:

```md
* [github] : the github website

[github]: https://github.com/
```
Then it produces:

* [github] : the github website

Which is correct.

I think it's parsing the whole bracket thing and the colon as a link reference like `[github]: https://github.com` and thus doesn't display it, which is incorrect.

Cheers.

[stone]: https://github.com/Armael/stone
[github]: https://github.com/

**Comment by nojb** [comment]
This is fixed in `trunk`. We are working to get the next version out the door as soon as possible. Thanks!

**Comment by zapashcanon** [comment]
Thanks a lot !
