### ISSUE TITLE
Proper way to deal with math

### ISSUE THREAD

**Issue by TheoWinterhalter** [ocaml/omd#194]
Hi, I'm wondering what is the proper way to deal with math in `1.3.1`, using `omd` as a library.
Currently I use `mathjax`or `katex` in the output html, but text in between `$...$`, `\[ ...\]`, `\(...\)` or `$$...$$` is still interpreted as markdown.
I guess I should add special hooks with `extension` and return `Some` to parse util the end delimiter myself, but that won't allow me to use `$` as delimiters right?

I guess this is somewhat related to #131 and it is also related to #114.

**Comment by XVilka** [comment]
Maybe it makes sense to reuse the code from [Patoline](http://patoline.org/) somehow? It has [typography/Maths.ml](https://github.com/patoline/patoline/blob/master/typography/Maths.ml) file with some implementation.

**Comment by TheoWinterhalter** [comment]
I'm also thinking, maybe the features from #191 can be used to do that? I mean if I can use some different syntax differentiating between inline and block that does not get parsed as markdown underneath and then print it in a format compatible with mathjax/katex, I would be very happy.

**Comment by TheoWinterhalter** [comment]
I ended up writing a preprocessor to put block maths in `<div>`s and inline math in `<span>`s but it seems only the first one gets ignored by omd.

**Comment by nojb** [comment]
There is no special support for it at the moment. We are thinking about how to support extensions, but this will only happen after 2.0 is released (which we are working towards).

**Comment by nojb** [comment]
Moved this one to #205
