### ISSUE TITLE
omd very slow on Tk.md

### ISSUE THREAD

**Issue by sanette** [ocaml/omd#199]
While working on the ocaml manual, I noticed that `omd` is quite slow on some files, for instance running `omd Tk.md` on the attached `Tk.md` file takes 100% cpu for more than 1 minute to complete. Any idea why?

[Tk.md.txt](https://github.com/ocaml/omd/files/4328412/Tk.md.txt)

**Comment by nojb** [comment]
Which version of `omd` are you using?

**Comment by sanette** [comment]
1.3.1

**Comment by nojb** [comment]
Could you try with `master` ? Unfortunately we still have not made a release as there are a couple of things that need to be solved beforehand, but it may useful to give it a try, as the engine was completely rewritten. To try, clone the repository and build with `dune`:

- `git clone https://github.com/ocaml/omd`
- `cd omd`
- `dune build`

The binary will be available at `_build/install/default/bin/omd`.

**Comment by sanette** [comment]
```
$ dune build
File "src/block.mli", line 17, characters 9-31:
Error: Only type constructors with identical parameters can be substituted.
File "src/parser.ml", line 464, characters 60-69:
Error: Unbound value Uchar.rep
```

**Comment by nojb** [comment]
What version of `ocaml` are you using ?

**Comment by sanette** [comment]
4.05.0
(I'm on ubuntu)

**Comment by nojb** [comment]
You will need to update to 4.06 at least to try `master`.

**Comment by sanette** [comment]
indeed with 4.08.1 with the master branch it's very fast on the same file

**Comment by nojb** [comment]
Cool. I will try to get a release through the door in the next few weeks, but can't commit to anything more than that as am rather busy at the moment.

**Comment by sanette** [comment]
ok thanks!
