### ISSUE TITLE
Convert from html

### ISSUE THREAD

**Issue by shonfeder** [ocaml/omd#200]
It's sometimes useful to parse into markdown from HTML

**Comment by nojb** [comment]
Could you say a few words about what you mean by this exactly? Thanks!

**Comment by shonfeder** [comment]
Ah, sorry. I just have in mind a function

```
of_html: html -> Omd.t
``` 

Where `html` is probably something like `TyXml.t` (since we probably don't want `Omd` to include an html parser), and the `Omd.t` would be the result of converting the obvious and standard tag to the corresponding Omd representation.

On further thought, this would probably be out of place in this lib! I'll close this :)
