### ISSUE TITLE
Lower OCaml requirement

### ISSUE THREAD

**Issue by jfrolich** [ocaml/omd#210]
Can we have some conditional compilation to make this library work under `4.04.2`. I think it would be great to make this accessible to most projects. I am dealing with a project that need to support `4.04` as the minimum version.

I did make it compile on 4.04 by removing `Fun.protect` and adding a `Compat` module for `Buffer.add_utf_8_uchar`, `List.find_opt`, `Uchar.rep`.

**Comment by nojb** [comment]
Hello, and thanks for opening this issue. We are currently preparing a new release and we will look into making it compatible with 4.04.

Just out of curiosity, can you say a few words why you are required to support 4.04 ? It is a rather ancient version of OCaml :)

**Comment by jfrolich** [comment]
We are planning to support (extended) markdown to ocamldoc compilation in the Reason toolchain, the Reason toolchain needs to support 4.04 for now.

**Comment by nojb** [comment]
OK, thanks.

**Comment by jfrolich** [comment]
This is why I am trying to create a printer to ocamldoc for `omd`. Might also be handy for other purposes. For odoc integration it would at least be cool to have markdown files be converted to ocamldoc and be included in the generated documentation.

**Comment by nojb** [comment]
Got it. Yes, getting to compile with 4.04 should not be too hard. Would you like to open a PR with your local patch?

**Comment by jfrolich** [comment]
Yes!
