### ISSUE TITLE
Lower dune requirement?

### ISSUE THREAD

**Issue by jordwalke** [ocaml/omd#212]
I noticed that the master branch of omd has ` "dune" {>= "2.5"}`

Is there a reason why this is needed?

It makes it more difficult for some packages or internal systems that have to be pinned to an earlier version of Dune, just as one example. Is there something really advanced going on in the build that requires >=2.5?

**Comment by nojb** [comment]
I will check. Which version would be OK for you?

**Comment by nojb** [comment]
I made #218, requiring only dune 2.0. Going lower than that would be a bit more work and I would rather not, since dune 1.0 is not actively maintained anymore and lacks some features that we are currently using.

Does this work for you? Thanks!

**Comment by shonfeder** [comment]
Just FYI, @jordwalke: we are planning to update dune to 2.7. That is still 2 minor versions behind the latest, and 3.0 is on the horizon, so I think it is reasonable for us to be looking forward to the latest.

I'll give that PR a day or two in case any discussion around it is needed, but I assume that if a project is able to get by pinning their dune version to =< 2.0 the can accommodate by pinning omd to a suitable version.
