### ISSUE TITLE
The AST representaiton of images and links seems inaccurate

### ISSUE THREAD

**Issue by shonfeder** [ocaml/omd#216]
If not inaccurate (perhaps there is no objective standard in matters of AST representations), it is at least counterintuitive (to me) and awkward to work with.

The markdown spec we test against says that

```
![foo](/url "title")
```

Should be parsed into

```
<p><img src="/url" alt="foo" title="title" /></p>
```

So, the content of the square braces should be the value of the `alt` attribute in the image tag. This seems to hold without any exception.

However, the current representation in the `Omd` ast is:

```
# Omd.of_string "![foo](/url \"title\")";;
- : Omd.doc =
[{Omd.bl_desc =
   Omd.Paragraph
    {Omd.il_desc =
      Omd.Image
       {Omd.label = {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
        destination = "/url"; title = Some "title"};
     il_attributes = []};
  bl_attributes = []}]
```

The value of the `label` field in the `image` record is `Omd.inline`. But that means valid values for this could include raw html, links, soft breaks, etc., when, judging from the spec, it looks like this should always just be a string.E.g., in this example:

```
![foo [bar](/url)](/url2)
.
<p><img src="/url2" alt="foo bar" /></p>
```

Moreover, as far as I can tell, it is impossible for the `li_attributes` field to ever have any use in this context. 

If the label is omitted, we get an even more confusing representation, in which the absence of a label is represented in the presence of an inline concatenation of no elements:

```
# Omd.of_string "![](/url \"title\")";;
- : Omd.doc =
[{Omd.bl_desc =
   Omd.Paragraph
    {Omd.il_desc =
      Omd.Image
       {Omd.label = {Omd.il_desc = Omd.Concat []; il_attributes = []};
        destination = "/url"; title = Some "title"};
     il_attributes = []};
  bl_attributes = []}]
```

IMO, from the perspective of the AST as a UI tool this inaccurate representation isn't worth whatever might be gained by sharing the `link_def` record. A more user friendly representation would be something like: 

```
type image = {alt: string option; title: string option; destination: string}
```

If you're open to this change, I'm happen to open a PR for it.

**Comment by shonfeder** [comment]
I'm just noticing some other surprising behavior, which also strikes me as very inconvenient, and not accurate to the semantics of the data model underlying markdown, based on my understanding. (Of course, it's possible this is because you intend something for this library which is different than I expect, or that I misunderstand in some other way!)

My naive assumption is that these two bits of markdown should compile down to the same AST:

```
[foo](/some/url)
```

```
[foo][label]

[label]: /some/url
```

This assumption is based on my understanding of the purpose of an AST in relation concrete surface syntax. These are two different ways of expressing that `foo` should be a link to `/some/url`. While the concrete syntax in these two examples is different, at an abstract level, they are just two ways of expressing the same data structure. However, these are parsed into two entirely different ASTs:

```
Omd.of_string "[foo](/some/url)";;
- : Omd.doc =
[{Omd.bl_desc =
   Omd.Paragraph
    {Omd.il_desc =
      Omd.Link
       {Omd.label = {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
        destination = "/some/url"; title = None};
     il_attributes = []};
  bl_attributes = []}]


Omd.of_string "[foo][label]

[label]: /some/url";;
- : Omd.doc =
[{Omd.bl_desc =
   Omd.Paragraph
    {Omd.il_desc =
      Omd.Link
       {Omd.label = {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
        destination = "/some/url"; title = None};
     il_attributes = []};
  bl_attributes = []};
 {Omd.bl_desc =
   Omd.Link_def {Omd.label = "label"; destination = "/some/url"; title = None};
  bl_attributes = []}]
``` 

This is fundamentally at variance from the approach used in earlier versions of Omd:

```
Omd.of_string "[foo][label]

[label]: /some/url";;
- : Omd.t = [Omd.Paragraph [Omd.Ref (<obj>, "label", "foo", <obj>)]
```

which is also the approach used in `pandoc`:

```
pandoc --from markdown --to native  <<< '[foo]

[foo]: /url "title"'
[Para [Link ("",[],[]) [Str "foo"] ("/url","title")]]
```

**Comment by shonfeder** [comment]
What `Omd.doc` currently exposes is a concrete syntax tree. I could definitely see how this would be useful, but I think that most users (but at least, myself as a user) will want to work with the abstract syntax tree. As one final example:

The current version parses the following

```markdown
![*foo* bar]

[*foo* bar]: /url "title"
```

as

```
Omd.of_string {|![*foo* bar]

[*foo* bar]: /url "title"
|};;
- : Omd.doc =
[{Omd.bl_desc =
   Omd.Paragraph
    {Omd.il_desc =
      Omd.Image
       {Omd.label =
         {Omd.il_desc =
           Omd.Concat
            [{Omd.il_desc =
               Omd.Emph {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
              il_attributes = []};
             {Omd.il_desc = Omd.Text " bar"; il_attributes = []}];
          il_attributes = []};
        destination = "/url"; title = Some "title"};
     il_attributes = []};
  bl_attributes = []};
 {Omd.bl_desc =
   Omd.Link_def
    {Omd.label = "*foo* bar"; destination = "/url"; title = Some "title"};
  bl_attributes = []}]
```

But, the semantics, according to the spec we use to test again, don't support allowing `Emph` in the "label" of an image. As a user, if I've parsed down markdown, I don't want to have to descend 8+ levels into the tree to retrieve the label, only to find out I have to post-process the result to remove invalid nodes.

**Comment by nojb** [comment]
> The value of the `label` field in the `image` record is `Omd.inline`. But that means valid values for this could include raw html, links, soft breaks, etc., when, judging from the spec, it looks like this should always just be a string.

Indeed the image description (the stuff between square brackets) is defined to be a sequence of inline elements, but when rendering only the plain string contents are usually used for the `alt` attribute. See https://spec.commonmark.org/0.29/#images.

When building the HTML representation, you can get the plain string contents of an inline by using the `Html.to_plain_text` function.

> Moreover, as far as I can tell, it is impossible for the `li_attributes` field to ever have any use in this context.

In principle it should be possible to attach attributes to any inline or block element. The current implementation does not actually do this for every case, and this should be fixed in the future, but there is no reason not to make the support generic. For example, in the case of image links, the syntax for attributes is `![foo](/url title){#id .class1 .class2 foo=bar ...}`.

**Comment by nojb** [comment]
> This assumption is based on my understanding of the purpose of an AST in relation concrete surface syntax. These are two different ways of expressing that `foo` should be a link to `/some/url`. While the concrete syntax in these two examples is different, at an abstract level, they are just two ways of expressing the same data structure. However, in the current version of Omd these are parsed into two entirely different ASTs:

Unless I am missing something, they are not entirely different: the only difference is that the second one includes the `Link_def` node. This is because previously we used to parse the second case to a different kind of node that referred to the `Link_def` node instead of directly including the link. I agree that nowadays the `Link_def` node is no longer useful and we could just remove it from the AST. This should be doable.

> ```
> Omd.of_string "[foo](/some/url)";;
> - : Omd.doc =
> [{Omd.bl_desc =
>    Omd.Paragraph
>     {Omd.il_desc =
>       Omd.Link
>        {Omd.label = {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
>         destination = "/some/url"; title = None};
>      il_attributes = []};
>   bl_attributes = []}]
> 
> 
> Omd.of_string "[foo][label]
> 
> [label]: /some/url";;
> - : Omd.doc =
> [{Omd.bl_desc =
>    Omd.Paragraph
>     {Omd.il_desc =
>       Omd.Link
>        {Omd.label = {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
>         destination = "/some/url"; title = None};
>      il_attributes = []};
>   bl_attributes = []};
>  {Omd.bl_desc =
>    Omd.Link_def {Omd.label = "label"; destination = "/some/url"; title = None};
>   bl_attributes = []}]
> ```

**Comment by nojb** [comment]
> The current version parses the following
> 
> ```gfm
> ![*foo* bar]
> 
> [*foo* bar]: /url "title"
> ```
> 
> as
> 
> ```
> Omd.of_string {|![*foo* bar]
> 
> [*foo* bar]: /url "title"
> |};;
> - : Omd.doc =
> [{Omd.bl_desc =
>    Omd.Paragraph
>     {Omd.il_desc =
>       Omd.Image
>        {Omd.label =
>          {Omd.il_desc =
>            Omd.Concat
>             [{Omd.il_desc =
>                Omd.Emph {Omd.il_desc = Omd.Text "foo"; il_attributes = []};
>               il_attributes = []};
>              {Omd.il_desc = Omd.Text " bar"; il_attributes = []}];
>           il_attributes = []};
>         destination = "/url"; title = Some "title"};
>      il_attributes = []};
>   bl_attributes = []};
>  {Omd.bl_desc =
>    Omd.Link_def
>     {Omd.label = "*foo* bar"; destination = "/url"; title = Some "title"};
>   bl_attributes = []}]
> ```
> 
> But, the semantics, according to the spec we use to test again, don't support allowing `Emph` in the "label" of an image. As a user, if I've parsed down markdown, I don't want to have to descend 8+ levels into the tree to retrieve the label, only to find out I have to post-process the result to remove invalid nodes.

It is not that `Emph` is not supported, it is just that the HTML backend is supposed to put that inline in the `alt` attribute so it must use the plain string contents of the inline when rendering. But other backends may want to take advantage of the styling information. In any case, I would rather stick to what the standard says here. And it is easy to convert the inline to a plain string using `Html.to_plain_text`.  Full details at https://spec.commonmark.org/0.29/#link-text

> So perhaps what this issue amounts to is a proposal to add an additional representation that provides a simple and convenient AST, like the one in previous versions of `Omd` (but without the objects :)).

I agree that the line between "concrete" and "abstract" is not very clear sometimes, but in the above case of link text, the standard explicitly allows styling, so I would rather stick to it. Are there any other instances where you find the current AST not "abstract enough"?

**Comment by nojb** [comment]
I opened a PR to remove the `Link_def` node #217

**Comment by shonfeder** [comment]
Thanks for your careful response to my long, rambling issue :)

I'll note that, while my feedback stems from the Tyxml work, it is coming from a place of a user consuming the UI of the librar -- it's not a roundabout way of asking for help with the Tyxml port (I'll definitely ask for that directly if I get stuck :slightly_smiling_face:).

After reviewing the parts of the common mark spec you referred me to, I know see the reasoning behind the structure quite clearly. I think I've become used to dealing with representations of markdown where the semantics are assumed to be the same a subset of the html the markdown would compile down to. But from the perspective of commonmark, that you are adopting here, the semantics of the markdown is its own thing, and HTML is just one possible rendering. From this perspective, I now see that the inline components are not a matter of leaking concrete details into the AST :)

From this perspective, I honestly don't know whether link reference definitions should be included in the AST!

**Comment by nojb** [comment]
On the contrary, it is great to have this kind of feedback! Thanks!
