### ISSUE TITLE
benchmark wiki page

### ISSUE THREAD

**Issue by gasche** [ocaml/omd#226]
Dear omd developers,

I was curious of how `omd` fares compared to other Markdown parsers in term of performances. I did some quick testing and put the results in a [Benchmarks wiki page](https://github.com/ocaml/omd/wiki/Benchmarks). (Weird story: it looks like Github wiki does not support Markdown syntax for tables, but it does support tables when using org-mode syntax, so I used that.)

The summary is that omd 1.x was faster than Pandoc but slower than a popular Javascript library I tried (markdown-it), and omd 2.x is faster. It probably still wouldn't qualify as "one of the fastest implementations" (there are very ugly implementations that do everything in a single regexp), but it is state-of-the-art fast among tools in regular usage by the web community.

Thanks!

(This issue was just for notification -- I suspect that Github does not notify watchers when a new wiki page is created. Feel free to close it immediately.)

**Comment by nojb** [comment]
Hi Gabriel,

Thanks a lot for having made the benchmark and taken the time to create the wiki page! Also, it is nice to know that the version in `master` does not do too badly :) 

The project itself is kind of stalled at the moment; I am the nominal maintainer but don't have the time (or the need) to push it forward. There was a lot of work on the current `master`, but the "2.0" has not yet been released, and no-one is actively working on it.

I would be more than happy to pass maintainership to someone who had the time and willingness to take over, as the current state of the project makes me sad.

**Comment by gasche** [comment]
> I would be more than happy to pass maintainership to someone who had the time and willingness to take over

I'm sure you wrote this line with no ulterior motives, but let me clarify for other participants that this "someone" certainly is not me!

I think that you could do the following:
- ask @clecat 
- post a request for new contributors/maintainers on Discuss
- create a tag for the current version, possibly a new 2.0-alpha, to have a stable name to refer to it

**Comment by nojb** [comment]
> > I would be more than happy to pass maintainership to someone who had the time and willingness to take over
> 
> I'm sure you wrote this line with no ulterior motives, but let me clarify for other participants that this "someone" certainly is not me!

Indeed, I didn't mean it that way :)

> 
> I think that you could do the following:
> 
> * ask @clecat
> * post a request for new contributors/maintainers on Discuss
> * create a tag for the current version, possibly a new 2.0-alpha, to have a stable name to refer to it

Thanks for the suggestion, I think I will do this.

**Comment by clecat** [comment]
Hello there,
To be fair, it has been a long time since I gave `omd` a bit of my time.
In the paper I think the project is really cool and trying to invest some time on it is totally fine by me.
However I dont know how much of it I would be able to give to the project, and how, in long terms speaking, I would be able to sustain it.
