### ISSUE TITLE
Could we refine the representation of the AST?

### ISSUE THREAD

**Issue by shonfeder** [ocaml/omd#228]
I think we could make some tweaks to the current AST representation that would improve the API, while still supporting all the current information. I'm making a suggestion here, but I am not attached to the particulars. I just want to start a conversation to see if there is a willingness to explore a less noisy and cumbersome representation.

Compare these two representation in terms of readability:

```ocaml
let current : Ast.block list =
  let open Ast in
  [{bl_desc = Heading (1, {il_desc = Text "A document"; il_attributes = []});
    bl_attributes = []};
   {bl_desc =
      List (Bullet '-', Tight,
            [[{bl_desc = Paragraph {il_desc = Text "Item 1"; il_attributes = []};
               bl_attributes = []}];
             [{bl_desc = Paragraph {il_desc = Text "Item 2"; il_attributes = []};
               bl_attributes = []}];
             [{bl_desc = Paragraph {il_desc = Text "Item 3"; il_attributes = []};
               bl_attributes = []}]]);
    bl_attributes = []};
   {bl_desc =
      Paragraph
        {il_desc =
           Link
             {label = {il_desc = Text "and a link"; il_attributes = []};
              destination = "./somewhere"; title = None};
         il_attributes = []};
    bl_attributes = []}]

let propsed : Alt_rep.doc =
  let open Alt_rep in
  [ Heading ([], 1, [Text "A document"]);
    List ([], Bullet '-', Tight,
          [Paragraph ([], [Text "Item 1"]);
           Paragraph ([], [Text "Item 2"]);
           Paragraph ([], [Text "Item 3"])]);
    Paragraph ([], [Link ([],
                          {label = Text "and a link";
                           destination = "./somewhere";
                           title = None})])]
```

The latter has a type like

```ocaml
type attrs =
  (string * string) list

type link =
  {
    label: inline;
    destination: string;
    title: string option;
  }

and inline =
  | Concat of attrs * inline list
  | Text of string
  | Emph of attrs * inline
  | Strong of attrs * inline
  | Code of attrs * string
  | Hard_break
  | Soft_break
  | Link of attrs * link
  | Image of attrs * link
  | Html of attrs * string
```

We can see that this gives completely unambiguous fields, and it is dead easy to tell which kind of node you are in at a glance. It also supports all of the same information as the current AST. 

IMO readability of the AST and the ergonomics of manipulating it are very important, since the AST is really the main API for this library.

**Comment by sonologico** [comment]
I like your suggestion. Going in that direction would make it more readable and we could easily add a function to get the attributes field.

What do you think of this? https://github.com/sonologico/omd/blob/sonologico/alt-ast/src/ast.ml

Main changes:
* Inline the attribute field as you suggest
* Remove functors. There's no need for them if the argument signature contains only a type
* Make the types generic over attributes as well. This could give us a way to support locations and extra details for users that care about it in a lightweight manner.

Just a suggestion for discussion. I haven't bothered to update the rest of the code yet.

**Comment by jfrolich** [comment]
Perhaps use inline records to make the variants more descriptive?

**Comment by shonfeder** [comment]
@sonologico I really like it! Do you want to open a PR to start staging this change set? 

(I'm happy to help propagate your changes through, if you'd find that helpful btw. Just let me know.) 

I *think* aiming to address the desire for more detailed information by having a parametric attribute argument is an excellent approach. 

Perhaps we should have 

```ocaml
type 'attrs t = ('attrs inline, 'attrs) block
```

So that the "full" (i.e. not raw) ast is type is always understood to have the same type for attributes in blocks and inlines? Prima facie, this seems like a reasonable invariant to me. 

Then, iiuc, we support source mapping with something like:

```ocaml
type loc = {line: int, char: int}
type attrs_with_loc = {attr: attributes; loc: loc}
type with_source = attrs_with_loc t
```

Along with a function

```ocaml
let to_loc : attrs_with_loc t -> loc
```

Is that the idea?

**Comment by shonfeder** [comment]
> Perhaps use inline records to make the variants more descriptive? I recently did some refactoring, and I found variants with multiple payloads are much nicer to work with if they have inline records.

@jfrolich when I look at the current AST @sonologico has suggested, it seems that the types of each component produce very descriptive, and unambiguous, type of the overall AST at each level. E.g., the constructor for a paragraph of type `t` looks like:

```ocaml
Paragraph of attributes * attributes inline list
```

An ordered list looks like

```ocaml
List of attributes * list_type * list_spacing * t list list
```

This all looks pretty explicit to me. If you think there's some ambiguity or unclarity that would be helped with inline records, could you give an example? Thanks!

**Comment by sonologico** [comment]
> Perhaps use inline records to make the variants more descriptive? I recently did some refactoring, and I found variants with multiple payloads are much nicer to work with if they have inline records.

@jfrolich, in this particular case, I would personally be more inclined to go with plain variants. I wouldn't mind using inline records if that's what most folks want.

**Comment by sonologico** [comment]
> @sonologico I really like it! Do you want to open a PR to start staging this change set?
> 
> (I'm happy to help propagate your changes through, if you'd find that helpful btw. Just let me know.)

I'll open a PR later tonight then. We can discuss concrete details there. Thanks. I'll message you if I think I won't have enough time to finish it in a timely manner. 

> Perhaps we should have
> 
> ```ocaml
> type 'attrs t = ('attrs inline, 'attrs) block
> ```

This sounds like a good restriction. As long as we expose `block`, I don't have a strong preference either for having `t` be parameterized by `'attrs` or having it already concrete with `attributes`. I can see the benefit of having it as you suggested. So if you prefer that, I think we should go with it.
 
> Is that the idea?

Yes.
