### ISSUE TITLE
omd2: provide table of contents generation

### ISSUE THREAD

**Issue by avsm** [ocaml/omd#232]
(noting a missing feature from the omd 1.x branch, that was used in opam2web)

omd 1.x provided a [Omd.toc](https://github.com/ocaml/omd/blob/1.2.5/src/omd.mli#L151) function for table-of-contents generation. The [implementation](https://github.com/ocaml/omd/blob/1.2.5/src/omd.ml#L121) may be re-usable, with the new AST types.

**Comment by shonfeder** [comment]
Thanks for reporting the omission! I'm considering recovery of this functionality higher priority, but I'd like to settle #223 and #228 first, to minimize rework.

**Comment by sonologico** [comment]
Started working on this on #240.

**Comment by avsm** [comment]
Closed by #240 -- it's certainly enough for ocaml.org to generate its ToC. Thanks @sonologico !
