### ISSUE TITLE
failing verification of spec unit 516: invalid parsing of nested links

### ISSUE THREAD

**Issue by shonfeder** [ocaml/omd#245]
```diff
diff --git a/tests/spec-516.html b/tests/spec-516.html.new
index 43f8457..1c9a1cf 100644
--- a/tests/spec-516.html
+++ b/tests/spec-516.html.new
@@ -1 +1 @@
-<p><img src="uri3" alt="[foo](uri2)" /></p>
+<p>![[<a href="uri1">foo</a>](uri2)](uri3)</p>
```

Example in spec 

```markdown
![[[foo](uri1)](uri2)](uri3)
.
<p><img src="uri3" alt="[foo](uri2)" /></p>
```
https://github.com/madroach/omd/blob/master/tests/spec.txt#L7844-L7846

Exemplifying rule

> However, links may not contain other links, at any level of nesting.

Required for #235

**Comment by sonologico** [comment]
I was about to pick this one up, but I don't how the example works. It seems like the `ur1` is being dropped, which is not what I would expect.

Commonmark.js does give that result, but others give different results. https://johnmacfarlane.net/babelmark2/?text=!%5B%5B%5Bfoo%5D(uri1)%5D(uri2)%5D(uri3)

**Comment by sonologico** [comment]
I'm trying slightly different examples, but I can't figure out the expected behaviour.

https://johnmacfarlane.net/babelmark2/?text=!%5B%5B%5Bfoo%5D(uri1%5D(uri2)%5D(uri3)%0A%0A%0A%0A!%5B%5B%5Bfoo%5D(uri1)%5D%5Bbar%5D(uri2)%5D(uri3)
