### ISSUE TITLE
(Option to) Automatically fill the `id` attributes of the headings

### ISSUE THREAD

**Issue by smondet** [ocaml/omd#251]
It's implemented in `ood`:

- `slugify`: https://github.com/ocaml/ood/blob/7b2e15544ba90cca5f6a5baf606a3761ed62742b/src/ood-gen/lib/utils.ml#L37 (can be easily reimplemented without `str`)
- `doc_with_ids`: https://github.com/ocaml/ood/blob/7b2e15544ba90cca5f6a5baf606a3761ed62742b/src/ood-gen/lib/tutorial.ml#L36-L64

it'd be nice to have in `omd`, also to make sure there is a bit of standardization (maybe choose same IDs as pandoc).

**Comment by shonfeder** [comment]
I think this is a good idea.

**Comment by tatchi** [comment]
Hey 👋

I would be happy to work on that issue if nobody started yet :)
