### ISSUE TITLE
Add --version flag to CLI

### ISSUE THREAD

**Issue by shonfeder** [ocaml/omd#253]
Seems this was dropped in the rewrite, but is handy and standard on unixy tools.

**Comment by EllipticCrab** [comment]
I'd be happy to implement this, I'll throw up a PR when I get some free cycles!

**Comment by shonfeder** [comment]
Thanks @EllipticCrab! That would be much appreciated. Please let us know if you need any support along the way.

**Comment by EllipticCrab** [comment]
I just created a branch but I realize adding a dependency just to print version might not be desirable (considering `omd` does not have any dependencies beyond base). The trade-off is needing to add another place in code to track the version. Any preference?

https://github.com/ocaml/omd/pull/264

The dependency is a dune library: https://dune.readthedocs.io/en/latest/dune-libs.html#dune-build-info-library
