### ISSUE TITLE
command-line option to convert protocol-less URLs to absolute URL

### ISSUE THREAD

**Issue by pw374** [ocaml/omd#33]
The reason I want a command-line option to convert protocol-less URLs to absolute URLs is that I think it's necessary if you generate feeds, but I'm not even a 100% sure since the w3c validator validated a feed that contains relative links. I'll have to double-check that...

**Comment by nojb** [comment]
This kind of thing can already be done by using the intermediate representation exposed by the library (version in `master`), but not in a very nice way. I am thinking how to expose ways to customize the translation of markdown to its intermediate representations which would allow such kinds of rewritings. But this will only come after we get 2.0 out the door, so I'm closing this for now, and we can reopen later on as necessary.
