### ISSUE TITLE
Use <a name>, not ``id`` for the table of contents

### ISSUE THREAD

**Issue by Chris00** [ocaml/omd#39]
The anchors for the sections should use `<a name=""></a>` and not the `id` attribute.  Indeed the later has several uses in CSS.  It would moreover be convenient for `ocaml.org` because one wants to add

<pre>
a[name] {
  padding-top: 75px;
  margin-top: -70px;
  display: inline-block;
}
</pre>

to avoid anchors to fall under the navigation bar.  Doing this for `[id]` is very bad — it has all sorts of side effects that one does not want.  I thought to do it solely for `h1[id]`,.. but even that had unwanted effects.  It is better if the two

A related problem is the name of the anchor when several titles are be identical (maybe you already care for that, I did not check the code).

**Comment by nojb** [comment]
The table of contents stuff is not really present in the current `master`. The idea is that it should be possible to implement it client-side using the intermediate representation exposed by the library. So let us close this and revisit it if necessary.
