### ISSUE TITLE
Change spaces in URLs to %20

### ISSUE THREAD

**Issue by Chris00** [ocaml/omd#42]
Following on https://github.com/pw374/omd/pull/41#issuecomment-28289214, it seems that spaces in URLs should be replaced by `%20`.

**Comment by nojb** [comment]
Spaces in links, as in `[foo](https://bar foo)`, are not standard markdown. As we are focusing on getting a first release of version 2 out the door with strict support for commonmark, I'm closing this for now. Thanks!
