### ISSUE TITLE
Build rendering functions upon objects

### ISSUE THREAD

**Issue by Chris00** [ocaml/omd#79]
I think it would be nice that rendering functions (e.g. `Omd.to_html`) are built upon objects (in `Omd` or in `Omd_backend`).  With one method per constructor, that allows a user to redefine the output for a certain type of constructions (I was thinking to add a `_blank` to all external URLs) while benefiting from the default behavior for the other ones.

**Comment by nojb** [comment]
The current `master` has been completely rewritten and the current suggestion does not longer apply as-is. Furthermore I am thinking how to allow the user to customise the translation of Markdown into different representations, but this will only happen once we release version 2.
