### ISSUE TITLE
changes to come

### ISSUE THREAD

**Issue by pw374** [ocaml/omd#86]
What I plan to do soon:
- get rid of all top-level values of type `_ ref` in all modules except `Omd_main` (already partly done)
- finish the implementation of the extensions mechanism, and somehow that will address #84 
- try to implement properly something to address #27 (utf-8 support) (as soon as this one has been addresses, omd will switch to version 1.x.x)

**Comment by shonfeder** [comment]
I wonder if this issue is still relevant? It's very stale. :)

**Comment by pw374** [comment]
With the large refactoring that has happened (and everything else), this has indeed become quite irrelevant.
