### ISSUE TITLE
The -toc flag has no effect

### ISSUE THREAD

**Issue by yallop** [ocaml/omd#88]
The [`-toc`](https://github.com/pw374/omd/blob/6c5045e7/src/omd_main.ml#L276-L277) command-line option has no effect because [tag_toc](https://github.com/pw374/omd/blob/6c5045e7/src/omd_main.ml#L161-L213) is never called.

**Comment by nojb** [comment]
This is no longer supported directly in `master`. The idea is that the user should be able to implement such TOC-like functionality directly on the client-side by using the exposed intermediate representation exposed by the library. I'm closing this as am trying to focus on the real remaining issues to getting version 2 out the door. Thanks!
