### ISSUE TITLE
Add a `Raw` case in `Omd.element`

### ISSUE THREAD

**Issue by smondet** [ocaml/omd#98]
It would be useful to have a `Raw` or (`Bypass`) case in `Omd.element`. That case would be pasted without any escaping when rendering with `to_markdown` or `to_html`.

This is useful for extensions/preprocessors that output with `to_markdown` (for example to generate LaTeX with `pandoc`), right now I'm using `Html` and I think I'm lucky that no entity or special character gets escaped.

(maybe the other way of doing would be to add a `to_markdown: t -> string option` method to the extension object)

**Comment by nojb** [comment]
This should be dealt with with a proper extension API, but in any case does not apply to `master` as-is because the representation has been completely rewritten. Let's close this and re-open as needed.
